language: node_js

node_js:
  - "10.15.3"

script:
  - node --version
  - npm install
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $JOTTSTYLE_TOKEN
  local-dir: build
  keep-history: true
  on:
    branch: master

git:
  depth: 10